yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('posts/<int:post_id>/', views.post_view, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'


urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/pasword_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {% now "Y" %} Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
{% load static %}

<header>
  <nav class="my-navbar my-navbar-light">
    <div class="my-container">
      <a class="my-navbar-brand" href="{% url 'posts:index' %}">
        <img src={% static "img/logo.png" %} width="36" height="36" class="my-d-inline-block" alt="">
        <div class="my-brand"><span style="color:red">Ya</span>tube</div>
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="my-header-nav">
          <li class="my-header-nav-item">
            <a href="{% url 'about:author' %}" class="my-header-nav-link
              {% if view_name  == 'about:author' %}
              my-link-active
              {% endif %}">
              Об авторе
            </a>
          </li>
          <li class="my-header-nav-item">
            <a href="{% url 'about:tech' %}" class="my-header-nav-link
              {% if view_name  == 'about:tech' %}
              my-link-active
            {% endif %}">
              Технологии
            </a>
          </li>
          {% if user.is_authenticated %}              
            <li class="my-header-nav-item">
              <a href="{% url 'posts:post_create' %}" class="my-header-nav-link
                {% if view_name  == 'posts:post_create'%}
                my-link-active
                {% elif view_name  == 'posts:post_edit'%}
                my-link-active
                {% endif %}">
                Новая запись
              </a>
            </li>
            <li class="my-header-nav-item">
              <a href="{% url 'users:password_change' %}" class="my-header-nav-link my-header-nav-link-white
                {% if view_name  == 'users:password_change' %}
                my-link-active
                {% endif %}">
                Изменить пароль
              </a>
            </li>
            <li class="my-header-nav-item">
              <a href="{% url 'users:logout' %}" class="my-header-nav-link my-header-nav-link-white">Выйти</a>
            </li>
            <li class="my-header-nav-item">
              Пользователь: <a href="{% url 'posts:profile' user.username %}">
                                {{ user.username }}
                            </a>
            </li>
          {% else %}
            <li class="my-header-nav-item">
              <a href="{% url 'users:login' %}" class="my-header-nav-link my-header-nav-link-white
                {% if view_name  == 'users:login' %}
                my-link-active
                {% endif %}">
                Войти
              </a>
            <li class="my-header-nav-item">
              <a href="{% url 'users:signup' %}" class="my-header-nav-link my-header-nav-link-white
                {% if view_name  == 'users:signup' %}
                my-link-active
                {% endif %}">
                Регистрация
              </a>
          {% endif %}
        </ul>        
      {% endwith %}
    </div>
  </nav>
</header>